config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :api
  root "general_settings#index"
  post '/api/sync_ticket', to: "api#sync_ticket"
  get '/access_settings', to: "api#access_settings"
  post '/generate/api_key', to: "api#generate_api_key"
  post '/upate_sla_settings', to: "sla_settings#slaUpdate"

  resources :general_settings
  resources :tickets
  resources :user_settings
  resources :sla_settings
  resources :business_hours
  resources :holidays
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  validates :description , :date, :uniqueness => {:case_sensitive => true}
  validates :description, :date, :presence => true
  validates :description, :length => {:maximum => 250}
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  def index
    @holidays = Holiday.all
  end

  def new
    @holiday = Holiday.new
  end

  def create
    @holiday = Holiday.new(holiday_settings_params)
    if @holiday.save
      redirect_to "/holidays", notice: "Holidays Saved" 
    else
      render "new"
    end
  end

  def edit 
    @holiday = Holiday.find(params[:id])   
  end

  def update
    @holiday = Holiday.find(params[:id])
    if @holiday.update(holiday_settings_params)
      redirect_to "/holidays", notice: "Holiday saved"
    else
      render "new"
    end
  end

  def destroy
    @holiday = Holiday.find(params[:id])
    @holiday.destroy
    redirect_to "/holidays", notice: "Holiday was successfully deleted"
  end

  private
  def holiday_settings_params
    params.require(:holiday).permit(:id,:date,:description)
  end  
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/edit.html.erb
<%= form_for @holiday, method: "PUT" do |f| %> 
<div class="row mt-3 mb-3 ml-3 mr-3">
  <div class="col">
    <b>Holiday Settings</b>
  </div>
  <div class="col text-right">
    <%= f.submit "Update Settings", class: "btn btn-sm btn-primary mr-3 btn-sm" %>
    <a href="/holidays" class="btn btn-secondary btn-sm"><i class="fas fa-times"></i> Cancel</a>
  </div>
</div>
<div class="row pl-3 pr-3 ml-3 mr-3">
  <div class="col border-gray pt-3 rounded bg-gray form-group">
    <div class="row pb-2">
     <div class="col-6">Date</div>      
    </div>
    <div class="row">   
      <div class="col-6"> 
        <%= f.date_field :date , value: "#{@holiday.date}", class:"form-control form-control-sm"%>
      </div>                  
    </div>
    <div class="row pt-4">
      <div class="col-6">
        <p>Description</p>
      </div>     
    </div>
    <div class="row pb-4">
      <div class="col-6">
        <%= f.text_area :description , value: "#{@holiday.description}", rows: 5, class:"form-control form-control-sm"%>
      </div>       
    </div>
  </div> 
</div>  
<% end %>

app/views/holidays/index.html.erb
<div class="row mt-3 mb-3 ml-3 mr-3">
  <div class="col">
    <b>Holiday Settings</b>
  </div>
  <div class="col text-right">  
    <a href="/holidays/new" class="btn btn-primary btn-sm">Add Holidays</a>
  </div>
</div>
<div class="row pl-3 pr-3 ml-3 mr-3">
  <div class="col border-gray rounded bg-gray form-group">    
      <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Description</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
        <% @holidays.each do |holiday| %>
          <tr>            
            <td><%= holiday.date %></td>
            <td style="width : 850px"><p><%= holiday.description%></p></td>
            <td>
              <%= link_to '<i class="fas fa-pencil-alt"></i> Edit'.html_safe, edit_holiday_path(holiday), :class => "mr-3"%>
              <%= link_to '<i class="fas fa-trash-alt"></i> Delete'.html_safe, holiday_path(holiday) , method: :delete, data: {confirm: "Are you sure?"}, :class => "text-danger"%>
            </td>
          </tr>  
        <% end %>
      </tbody>
    </table>
  </div> 
</div>  

app/views/holidays/new.html.erb
<%= form_for @holiday, method: "POST" do |f| %> 
<div class="row mt-3 mb-3 ml-3 mr-3">
  <div class="col">
    <b>Holiday Settings</b>
  </div>
  <div class="col text-right">
    <%= f.submit "Save Settings", class: "btn btn-sm btn-primary mr-3 btn-sm" %>
    <a href="/holidays" class="btn btn-secondary btn-sm"><i class="fas fa-times"></i> Cancel</a>
  </div>
</div>
 <% if @holiday.errors.full_messages.any? %>
    <% @holiday.errors.messages.values.each do |error_message| %>     
      <%= puts "-----------#{error_message.first}----------"%>
      <script>toastr.warning('<%= error_message.first %>')</script>
    <% end %>     
  <% end %>    
<div class="row pl-3 pr-3 ml-3 mr-3">
  <div class="col border-gray pt-3 rounded bg-gray form-group">
    <div class="row">
     <div class="col-6">
        <%= f.label :date , "Date"%>
      </div>      
    </div>
    <div class="row">
     <div class="col-6">
       <%= f.date_field :date,"data-provide"=>'datepicker',class: 'form-control form-control-sm'%>      
      </div>   
    </div>    
    <div class="row pt-4">
      <div class="col-6">
      <%= f.label :description, "Description" %>
      </div>
    </div>   
    <div class="row pb-4">
      <div class="col-6">
        <%= f.text_area :description, rows: 5, class: 'form-control form-control-sm' %>
      </div>
    </div>                
  </div> 
</div>  
<% end %>